version: '3.7'
services:
  pihole: # https://github.com/pi-hole/docker-pi-hole/blob/master/README.md
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: 'host'
    env_file: 
      - pihole.env
      - pihole-secret.env
    volumes:
       - './pihole/:/etc/pihole/'
       - './dnsmasq/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
