version: '3.7'
services:
  unifi: # https://hub.docker.com/r/linuxserver/unifi-controller
    image: linuxserver/unifi-controller:amd64-latest
    container_name: unifi
    networks:
      - unifi
    ports:
      - "1900:1900/udp"
      - "3478:3478/udp"
      - "6789:6789/tcp"
      - "8080:8080/tcp"
      - "8081:8081/tcp"
      - "8443:8443/tcp"
      - "8843:8843/tcp"
      - "8880:8880/tcp"
      - "10001:10001/udp"
    volumes:
      - ./config:/config
    environment:
      - TZ=Europe/Copenhagen
      - PUID=1000
      - PGID=1000
      - MEM_LIMIT=1024M
    restart: unless-stopped
    
networks:
    unifi:
  